### ISSUE TITLE
Package.swift needs upgrade for swift 4.

### ISSUE THREAD

**Issue by sdrpa** [freshOS/then#31] opened 2017-09-27 09:45 UTC
I tried to use 3.0.0 in a project, compiling with Swift 4.0 from command line ... Got:

```
.../Source/Promise.swift:204:9: error: 'promiseProgressCallBack' is inaccessible due to 'private' protection level
        promiseProgressCallBack = { resolve, reject, progress in
        ^

.../Promise.swift:39:17: note: 'promiseProgressCallBack' declared here
    private var promiseProgressCallBack: ((_ resolve: @escaping ((T) -> Void),
                ^

.../Promise.swift:218:9: error: 'promiseProgressCallBack' is inaccessible due to 'private' protection level
        promiseProgressCallBack = { resolve, reject, progress in
        ^

.../Promise.swift:39:17: note: 'promiseProgressCallBack' declared here
    private var promiseProgressCallBack: ((_ resolve: @escaping ((T) -> Void),
```

It seems if you're using swift 4 toolchain, when you build 'then' from command line, it's built using swift 3 mode due to old manifest file format.
Since Swift 4 changed access control rules the errors above appear.

When I changed 'then' Package.swift to:
```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
   name: "then",
   products: [
      .library(
         name: "then",
         targets: ["then"]),
      ],
   dependencies: [
   ],
   targets: [
      .target(
         name: "then",
         dependencies: [])
      ]
)
```
Project built with no errors.

I created a new subfolder 'then' inside Sources and moved the source files to the folder to be able to compile the code, since new package manager requires it... (I tried with path property but with no success)

> path: This property defines the path to the top-level directory containing the target's sources, relative to the package root. It is not legal for this path to escape the package root, i.e., values like "../Foo", "/Foo" are invalid.

**Comment by s4cha** [comment] 2017-09-27 10:25
@sdrp Thanks a ton for reporting this and finding a fix.
I am going to look into this :)

**Comment by s4cha** [comment] 2017-09-27 10:33
@sdrpa I've been able to reproduce the issue.
I think it's because promiseProgressCallBack is accessed in an extension (Promise.swift line 204). For some reason it works when building in Xcode but not through SPM.
Making promiseProgressCallBack internal instead of private fixes the issue on my side :)

**Comment by s4cha** [comment] 2017-09-27 10:36
Indeed, putting the extension "extension Promise where T == Void {"
in a separate file yields the same issue in Xcode. Somehow the fact that they were in the same file allowed them to be accessed while private.
I'll try to push a fix with next version today.
Cheers,

**Comment by s4cha** [comment] 2017-09-27 10:39
@sdrpa In the meantime pointing to commit cd0ebe1a0127d574ade0491048c2e6499ef9843c should work :)

**Comment by s4cha** [comment] 2017-09-27 13:19
@sdrpa can you confirm this is fixed in 3.0.1  https://github.com/freshOS/then/releases/tag/3.0.1 ?

**Comment by sdrpa** [comment] 2017-09-27 17:17
@s4cha yes, 3.0.1 compiles with no problems. Tested with XCode 9 and from command line.

**Comment by s4cha** [comment] 2017-09-28 14:43
Thanks for your help :)

**Closed as completed by s4cha** 2017-09-28 14:43 UTC

**Comment by byfoz** [comment] 2017-11-13 15:59
@s4cha Are you able to push 3.0.1 to CocoaPods ? I can't seem to pull in the new version. Thanks 👍

**Comment by s4cha** [comment] 2017-11-13 16:11
@CImrie maybe cocoapods is down?  https://isitdownorjust.me/cocoapods-org/

**Comment by byfoz** [comment] 2017-11-13 16:19
@s4cha seems that was temporary - I can only see v3.0.0 when on this page: 
https://cocoapods.org/?q=thenPromise

I can't seem to find v3.0.1 and therefore can't install it using cocoapods, which would be much preferred at the moment.

**Comment by s4cha** [comment] 2017-11-13 16:47
@CImrie My bad must have missed the pod deploy for the latest version :/ this should be good now :)
